In [514]:
import bempp.api
import numpy as np
bempp.api.PLOT_BACKEND = "paraview"

In [515]:
# parametros 
num_base = 65 #numero de iteraciones 30

In [516]:
grid = bempp.api.shapes.sphere(h=0.1)
grid.plot()

In [517]:
print("numero de elementos:", grid.number_of_elements)
print("numero de bordes:", grid.number_of_edges)
print("numero de vertices:", grid.number_of_vertices)

numero de elementos: 3216
numero de bordes: 4824
numero de vertices: 1610


In [518]:
vertices = grid.vertices

# Imprimir los vértices
for i in range(vertices.shape[1]):
    print(f"Vértice {i}: {vertices[:, i]}")
scale_factor = np.random.uniform(0.98, 1)
vertices[0, :] *= scale_factor # escalar en la dirección x
vertices[1, :] *= scale_factor # escalar en la dirección y

Vértice 0: [1. 0. 0.]
Vértice 1: [0. 1. 0.]
Vértice 2: [-1.  0.  0.]
Vértice 3: [ 0. -1.  0.]
Vértice 4: [ 0.  0. -1.]
Vértice 5: [0. 0. 1.]
Vértice 6: [0.99518473 0.09801714 0.        ]
Vértice 7: [0.98078528 0.19509032 0.        ]
Vértice 8: [0.95694034 0.29028468 0.        ]
Vértice 9: [0.92387953 0.38268343 0.        ]
Vértice 10: [0.88192126 0.47139674 0.        ]
Vértice 11: [0.83146961 0.55557023 0.        ]
Vértice 12: [0.77301045 0.63439329 0.        ]
Vértice 13: [0.70710678 0.70710678 0.        ]
Vértice 14: [0.63439328 0.77301045 0.        ]
Vértice 15: [0.55557023 0.83146961 0.        ]
Vértice 16: [0.47139674 0.88192127 0.        ]
Vértice 17: [0.38268343 0.92387953 0.        ]
Vértice 18: [0.29028468 0.95694034 0.        ]
Vértice 19: [0.19509032 0.98078528 0.        ]
Vértice 20: [0.09801714 0.99518473 0.        ]
Vértice 21: [-0.09801714  0.99518473  0.        ]
Vértice 22: [-0.19509032  0.98078528  0.        ]
Vértice 23: [-0.29028468  0.95694034  0.        ]
Vértice 

In [519]:
num_vertices = grid.vertices.shape[1]
num_elementos = grid.number_of_elements
random_vector = np.round(np.random.uniform(0.96, 1, num_vertices), 4)
print(random_vector)

[0.987  0.9832 0.9865 ... 0.9762 0.9914 0.9633]


In [520]:
# for i in range(num_vertices):
#     vertices[:, i] += vertices[:, i] * random_vector[i]

# new_grid = bempp.api.Grid(vertices, grid.elements)
# new_grid.plot()

In [521]:
v_perturbacion = np.empty((0, num_vertices))
A = np.empty((0, num_vertices))

for sup in range(num_base):
    num_vertices = grid.vertices.shape[1]
    random_vector = np.round(np.random.uniform(0, 0.02, num_vertices), 4)
    eps = np.round(np.random.uniform(0, 0.5), 4)
    print(random_vector)
    grid = bempp.api.shapes.sphere(h=0.1)
    vertices = grid.vertices
    for i in range(num_vertices):
        vertices[:, i] += vertices[:, i] * (random_vector[i]) #perturbar con el vector de coordenadas esfericas cos de t a cos de 2t  #* random_vector[i]   #* (random_vector[i] - 0.001) * (eps)
    scale_factor = np.random.uniform(1, 1.5)
    vertices[0, :] *= scale_factor # escalar en la dirección x
    vertices[1, :] *= scale_factor # escalar en la dirección y
    
    v_perturbacion = np.vstack([v_perturbacion, random_vector])
    new_grid = bempp.api.Grid(vertices, grid.elements)
    # new_grid.plot()
    dp0_space = bempp.api.function_space(new_grid, "DP", 0)
    p1_space = bempp.api.function_space(new_grid, "P", 1)
    identity = bempp.api.operators.boundary.sparse.identity(
        p1_space, p1_space, p1_space)     # p1_space, p1_space, dp0_space
    dlp = bempp.api.operators.boundary.laplace.double_layer(
        p1_space, p1_space, p1_space)  # p1_space, p1_space, dp0_space
    slp = bempp.api.operators.boundary.laplace.single_layer(
        p1_space, p1_space, p1_space) #dp0_space, p1_space, dp0_space

    @bempp.api.real_callable
    def dirichlet_data(x, n, domain_index, result):
        result[0] = np.cos(x[0] + x[1]) #np.cos(x[0] + x[1])   #= 1./(4 * np.pi * ((x[0] - .9)**2 + x[1]**2 + x[2]**2)**(0.5))
        
    dirichlet_fun = bempp.api.GridFunction(p1_space, fun=dirichlet_data)

    rhs = (.5 * identity + dlp) * dirichlet_fun
    neumann_fun, info = bempp.api.linalg.cg(slp, rhs, tol=1E-3)
    print(neumann_fun)
    neumann_vector = neumann_fun.coefficients
    A = np.vstack([A, neumann_vector])
    print(neumann_vector)

[0.0177 0.0027 0.0092 ... 0.0036 0.0056 0.0115]


c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.53682105 -0.47895527 -0.40955827 ...  1.00413544  0.23598533
  0.61535997]
[0.0023 0.0041 0.0148 ... 0.0159 0.0069 0.0144]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.62965387 -0.61803472 -0.81873847 ...  0.74904006  0.06241448
  0.71942509]
[0.0184 0.0017 0.0178 ... 0.0017 0.0117 0.0046]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.39640108 -0.23457354 -0.52239682 ...  0.78301127  0.13407159
  0.56314209]
[0.0108 0.0186 0.0024 ... 0.0006 0.0094 0.001 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.62183859 -0.75151094 -0.72512001 ...  1.14650563  0.1291324
  1.03256339]
[0.0027 0.0161 0.0077 ... 0.0189 0.0065 0.0118]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.23439419 -0.44300146 -0.36237039 ...  0.39085275  0.38691327
  0.46425787]
[0.0053 0.0169 0.0061 ... 0.0016 0.0062 0.0088]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.50336737 -0.56935706 -0.40993238 ...  0.82260708  0.29848662
  0.63415193]
[0.009  0.0192 0.0129 ... 0.0028 0.0088 0.0036]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.45126723 -0.61498318 -0.47439979 ...  0.91463406  0.25142709
  0.68474939]
[0.0068 0.0049 0.0127 ... 0.0014 0.0047 0.0101]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.40237398 -0.3359379  -0.48064654 ...  0.82392436  0.2137166
  0.61207958]
[0.0191 0.0081 0.0085 ... 0.0021 0.0065 0.0187]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.80745055 -0.69650813 -0.80088383 ...  1.02495916 -0.00904687
  0.70100511]
[0.0061 0.0037 0.0086 ... 0.0029 0.0011 0.013 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.471593   -0.37877656 -0.43592331 ...  0.85766971  0.34941346
  0.51764975]
[0.0102 0.0172 0.0149 ... 0.0142 0.0115 0.0156]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.47636596 -0.58590115 -0.5437756  ...  0.62946643  0.11799532
  0.55700912]
[0.0061 0.0058 0.0165 ... 0.0059 0.0088 0.0185]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.60682886 -0.63292272 -0.54678787 ...  0.8942097   0.11696758
  0.56262245]
[0.0057 0.0094 0.0169 ... 0.012  0.0083 0.0179]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.47694965 -0.70449074 -0.60614279 ...  0.77347399  0.16872329
  0.56944518]
[0.0101 0.0073 0.0125 ... 0.0115 0.0171 0.0148]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.4426556  -0.42576882 -0.5092056  ...  0.6268675   0.09249442
  0.47328228]
[0.0177 0.0101 0.0016 ... 0.0197 0.0044 0.0009]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.68007419 -0.52066714 -0.38971644 ...  0.58357838  0.27886235
  0.89474237]
[0.0121 0.0069 0.0003 ... 0.0014 0.0179 0.0025]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.48297511 -0.40670148 -0.39015431 ...  0.89680603  0.03306563
  0.77381811]
[0.0106 0.0113 0.0135 ... 0.0091 0.02   0.004 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.58390065 -0.61681716 -0.60776928 ...  0.81225951 -0.00148933
  0.82583924]
[0.0074 0.0113 0.0045 ... 0.0152 0.0195 0.0075]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.67667729 -0.665135   -0.51664494 ...  0.71020139 -0.11933393
  0.86327055]
[0.0086 0.0134 0.0068 ... 0.0158 0.0139 0.0104]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.6164121  -0.58804187 -0.67132823 ...  0.77023484  0.00882625
  0.81260589]
[0.0188 0.0012 0.0186 ... 0.0019 0.0056 0.0031]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.48084631 -0.26412532 -0.49517691 ...  0.83591869  0.37859331
  0.79509435]
[0.0145 0.0138 0.0089 ... 0.0191 0.0085 0.012 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.58184885 -0.56819837 -0.45417013 ...  0.49160361  0.23464347
  0.59484942]
[0.017  0.0096 0.0141 ... 0.0015 0.0118 0.0189]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.56359168 -0.2952902  -0.43031298 ...  0.85661477  0.1880026
  0.49143229]
[0.0101 0.0163 0.01   ... 0.0193 0.0018 0.0116]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.44262457 -0.52243994 -0.3871903  ...  0.49863572  0.24951696
  0.51084916]
[0.0011 0.0023 0.0022 ... 0.0125 0.0063 0.0098]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.19585694 -0.29695963 -0.25407132 ...  0.52680486  0.24257297
  0.57286383]
[0.0178 0.0012 0.01   ... 0.0116 0.0071 0.0171]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.42450092 -0.34503368 -0.42866753 ...  0.5920905   0.35957136
  0.49856316]
[0.011  0.0055 0.0024 ... 0.0077 0.0043 0.008 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.50417657 -0.51458785 -0.41167354 ...  0.75133664  0.19552032
  0.69721093]
[0.0145 0.02   0.0179 ... 0.0126 0.0163 0.0184]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.66893942 -0.67536917 -0.7436714  ...  0.7000829  -0.0505276
  0.47091013]
[0.0019 0.0072 0.0061 ... 0.0054 0.0063 0.0033]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.57494869 -0.69316261 -0.69024532 ...  1.00228786  0.07345453
  0.91072787]
[0.0089 0.0117 0.0109 ... 0.0017 0.0077 0.0168]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.55477598 -0.63053698 -0.56295395 ...  0.90455594  0.14993495
  0.52747986]
[0.0142 0.0118 0.0115 ... 0.0152 0.0183 0.0117]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.36167799 -0.44298161 -0.39731521 ...  0.61351324  0.19795839
  0.58205425]
[0.0011 0.008  0.0123 ... 0.0146 0.0066 0.0172]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.59381061 -0.69674215 -0.76906758 ...  0.89289029  0.32324109
  0.73569328]
[0.0097 0.0164 0.004  ... 0.0138 0.0008 0.0165]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.54392854 -0.65786085 -0.50955869 ...  0.60930838  0.46287713
  0.47801657]
[0.0158 0.013  0.0089 ... 0.0089 0.0087 0.0066]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.58944705 -0.58946655 -0.496105   ...  0.77166011  0.14453459
  0.7307912 ]
[0.004  0.0012 0.0013 ... 0.014  0.0107 0.0192]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.29767342 -0.24740303 -0.22956495 ...  0.6313539   0.38264163
  0.33262084]
[0.0183 0.0119 0.0137 ... 0.0062 0.0111 0.0041]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.38414694 -0.46382377 -0.44379244 ...  0.62227598  0.24007674
  0.58314181]
[0.0019 0.009  0.0052 ... 0.0061 0.0001 0.0095]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.35933575 -0.51458963 -0.45158916 ...  0.92149415  0.46389923
  0.67075253]
[0.0158 0.0156 0.0055 ... 0.0016 0.0142 0.008 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.49240029 -0.69802906 -0.49916111 ...  0.86566945  0.24705662
  0.68621437]
[0.0194 0.0176 0.0182 ... 0.0058 0.0023 0.0061]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.63545567 -0.63421743 -0.5372797  ...  0.79708015  0.35424664
  0.70229163]
[0.0102 0.0199 0.0169 ... 0.0128 0.0034 0.0062]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.51597876 -0.50408223 -0.59172082 ...  0.69100251  0.44773818
  0.74758197]
[0.0071 0.0159 0.0138 ... 0.0199 0.0107 0.0073]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.54283278 -0.62716363 -0.67198949 ...  0.53215582  0.33487667
  0.71099997]
[0.0008 0.0048 0.0169 ... 0.0076 0.0039 0.007 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.59704891 -0.71607991 -0.75719631 ...  0.95160414  0.18668378
  0.88591378]
[0.0148 0.017  0.0181 ... 0.0099 0.0057 0.013 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.64247254 -0.81173615 -0.70305053 ...  0.85114506  0.25424445
  0.70254799]
[0.0094 0.0112 0.0047 ... 0.0117 0.0113 0.0139]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.62554626 -0.55917588 -0.44111308 ...  0.66094875  0.07934142
  0.63695332]
[0.0041 0.0175 0.0131 ... 0.0046 0.0103 0.0093]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.58752142 -0.73410858 -0.72591985 ...  0.97783797  0.03738104
  0.71902441]
[0.0109 0.0012 0.0148 ... 0.0116 0.0065 0.0022]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.65248708 -0.58494021 -0.64397015 ...  0.74431127  0.24702472
  0.95134298]
[0.0072 0.0007 0.0086 ... 0.008  0.0022 0.0106]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.40166008 -0.33826519 -0.52317168 ...  0.7888157   0.30746928
  0.66538617]
[0.0141 0.009  0.0022 ... 0.0087 0.0053 0.0174]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.45279602 -0.28288963 -0.34220033 ...  0.69444177  0.35526616
  0.40267387]
[0.0022 0.0193 0.0193 ... 0.0061 0.0161 0.0183]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.39450572 -0.49470034 -0.52776577 ...  0.75669887 -0.07445331
  0.53101078]
[0.0131 0.0087 0.0108 ... 0.0036 0.002  0.0123]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.51654957 -0.46225327 -0.47795485 ...  0.93363561  0.27326175
  0.53968963]
[0.0084 0.003  0.0105 ... 0.0174 0.007  0.0113]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.65067292 -0.51608691 -0.6769787  ...  0.7833571   0.19009564
  0.74225242]
[0.0104 0.0199 0.0154 ... 0.015  0.0005 0.0023]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.61779268 -0.57852331 -0.65942921 ...  0.77517385  0.3805808
  0.85594344]
[0.0068 0.0044 0.0116 ... 0.0038 0.0032 0.0158]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.5609072  -0.63030905 -0.83345518 ...  0.91926905  0.29858757
  0.74058615]
[0.0189 0.0128 0.0115 ... 0.0078 0.0099 0.0052]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.54323988 -0.47840683 -0.55551579 ...  0.8273583   0.07740516
  0.74448613]
[0.0031 0.0084 0.0033 ... 0.0074 0.0151 0.0141]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.26321478 -0.35461358 -0.36857667 ...  0.73090376  0.13625995
  0.45811086]
[0.0092 0.0017 0.017  ... 0.0046 0.0105 0.0141]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.67477024 -0.67740544 -0.72954225 ...  0.93961679 -0.00379574
  0.66951711]
[0.0173 0.0124 0.0032 ... 0.0157 0.0174 0.0053]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.69799858 -0.55616118 -0.39190183 ...  0.64180248 -0.00260805
  0.78345895]
[0.0027 0.0155 0.0063 ... 0.0025 0.0052 0.0079]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.24541293 -0.43262139 -0.26167492 ...  0.73059619  0.27771712
  0.64883493]
[0.0063 0.018  0.015  ... 0.0085 0.0071 0.0023]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.3881185  -0.46988168 -0.48135642 ...  0.63840058  0.27387734
  0.70895494]
[0.0092 0.018  0.0105 ... 0.003  0.0064 0.003 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.28267054 -0.43150369 -0.26382571 ...  0.85493989  0.28586354
  0.62022926]
[0.0028 0.0141 0.0079 ... 0.0136 0.0048 0.0134]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.39221981 -0.56984673 -0.35663064 ...  0.53168853  0.37794072
  0.47344229]
[0.0059 0.0079 0.0067 ... 0.0112 0.0144 0.0112]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.58612352 -0.58551308 -0.53090855 ...  0.75832235  0.150547
  0.68390349]
[0.015  0.0191 0.0039 ... 0.0112 0.0143 0.014 ]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.44382578 -0.54301717 -0.30653969 ...  0.59294905  0.1537119
  0.40277624]
[0.0153 0.01   0.0121 ... 0.004  0.0011 0.0025]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.40689647 -0.42211694 -0.40776691 ...  0.70074603  0.35309213
  0.66709269]
[0.0075 0.015  0.0067 ... 0.0053 0.0128 0.0179]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.44495243 -0.48024804 -0.38801626 ...  0.8230534   0.19087748
  0.40229291]
[0.0038 0.0103 0.018  ... 0.0142 0.0139 0.0063]



c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


[-0.59089591 -0.78225057 -0.75999266 ...  0.70397291 -0.11735682
  0.90761191]


In [522]:
A = A.T
v_perturbacion = v_perturbacion.T
v_perturbacion.shape
A.shape
A

array([[-0.53682105, -0.62965387, -0.39640108, ..., -0.40689647,
        -0.44495243, -0.59089591],
       [-0.47895527, -0.61803472, -0.23457354, ..., -0.42211694,
        -0.48024804, -0.78225057],
       [-0.40955827, -0.81873847, -0.52239682, ..., -0.40776691,
        -0.38801626, -0.75999266],
       ...,
       [ 1.00413544,  0.74904006,  0.78301127, ...,  0.70074603,
         0.8230534 ,  0.70397291],
       [ 0.23598533,  0.06241448,  0.13407159, ...,  0.35309213,
         0.19087748, -0.11735682],
       [ 0.61535997,  0.71942509,  0.56314209, ...,  0.66709269,
         0.40229291,  0.90761191]])

In [523]:
U, S, Vt = np.linalg.svd(A)

print("U:", U)
print("S:", S)
print("Vt:", Vt)

U: [[-2.17041864e-02 -4.28654046e-02 -1.32453120e-02 ...  3.58624529e-02
   1.24419666e-03  1.60676240e-02]
 [-2.27361994e-02 -4.73609782e-02 -4.98570634e-03 ... -5.76546127e-02
  -3.53227265e-02  8.82301221e-03]
 [-2.22428739e-02 -6.37593113e-02 -9.80317522e-03 ...  7.53715752e-03
   1.53903144e-03  8.25948550e-03]
 ...
 [ 3.23439707e-02  1.60904050e-02  2.79074253e-02 ...  9.45645072e-01
   1.61811245e-03 -8.00982236e-03]
 [ 8.26958276e-03 -5.38389108e-02  2.66087598e-05 ... -5.52224193e-04
   9.36637928e-01 -2.02123585e-03]
 [ 2.77429423e-02  3.22979343e-02  6.79649185e-03 ... -9.59178662e-03
   3.03061489e-03  9.45311870e-01]]
S: [191.17371039  11.42258499   5.27386818   5.14065284   5.10946816
   5.04899913   4.97058288   4.94204735   4.88437823   4.88013266
   4.82848011   4.80719336   4.79313909   4.7828928    4.74140903
   4.67418317   4.66158829   4.64354775   4.59169793   4.58516499
   4.5426953    4.53366215   4.50888723   4.4933473    4.4605957
   4.44990496   4.41484018   

In [524]:
# (1-((S[0])**2)/((np.sum(S))**2))**0.5 #tolerancia

In [525]:
U_1 = U[:, :30]
perturbacion_L = np.round(np.random.uniform(0, 0.02, num_vertices), 4)
eps_L = np.round(np.random.uniform(0, 3), 4) #0.5
grid = bempp.api.shapes.sphere(h=0.1)
vertices = grid.vertices
for i in range(num_vertices):
        vertices[:, i] += vertices[:, i] * (perturbacion_L[i])  #(perturbacion_L[i] - 0.001) * (eps_L)
scale_factor = np.random.uniform(1, 1.5) #1.5
vertices[0, :] *= scale_factor # escalar en la dirección x
vertices[1, :] *= scale_factor # escalar en la dirección y
grid_L = bempp.api.Grid(vertices, grid.elements)
# grid_L.plot()
dp0_space_L = bempp.api.function_space(grid_L, "DP", 0)
p1_space_L = bempp.api.function_space(grid_L, "P", 1)
V_L = bempp.api.operators.boundary.laplace.single_layer(
    p1_space_L, p1_space_L, p1_space_L)  #dp0_space_L, p1_space_L, dp0_space_L
V_L_matrix = V_L.weak_form().A

identity_L = bempp.api.operators.boundary.sparse.identity(
    p1_space_L, p1_space_L, p1_space_L)  #p1_space_L, p1_space_L, dp0_space_L
dlp_L = bempp.api.operators.boundary.laplace.double_layer(
    p1_space_L, p1_space_L, p1_space_L) #p1_space_L, p1_space_L, dp0_space_L

@bempp.api.real_callable
def dirichlet_data(x, n, domain_index, result):
    result[0] = np.cos(x[0]+ x[1])   #1./(4 * np.pi * ((x[0] - .9)**2 + x[1]**2 + x[2]**2)**(0.5))

dirichlet_fun_L = bempp.api.GridFunction(p1_space_L, fun=dirichlet_data)
rhs_L = (.5 * identity_L + dlp_L) * dirichlet_fun_L

neumann_fun_L, info_L = bempp.api.linalg.cg(V_L, rhs_L, tol=1E-3)
neumann_vector_L = neumann_fun.coefficients

c:\Users\Benja\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:394: SparseEfficiencyWarning: splu converted its input to CSC format
  warn('splu converted its input to CSC format', SparseEfficiencyWarning)


In [526]:
rhs_L_vector = rhs_L.projections(p1_space_L)
identity_L_matrix = identity_L.weak_form().A


In [527]:
# from scipy.sparse import csc_matrix
# from scipy.sparse.linalg import spsolve

# I = csc_matrix(np.eye(*identity_L_matrix.shape))
# identity_L_matrix_inv = spsolve(identity_L_matrix, I)

In [528]:

a = U_1.T  @ V_L_matrix @ U_1 #@ identity_L_matrix_inv
b = U_1.T  @ rhs_L_vector

# Resolviendo para x
x = np.linalg.solve(a, b)

In [529]:
(np.linalg.norm((U_1 @ x) - neumann_vector_L)) / (np.linalg.norm(neumann_vector_L)) #error 0.1458403 con 30, con 40 0.0673

0.1581764271279679

In [530]:

grid_L.plot()